[package]
name = "parser_cli"
version = "0.1.0"
edition.workspace = true
about.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
parser_expr = {workspace = true}